version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod  # Targets the Nginx production stage
    ports:
      - "80:80"
    restart: unless-stopped